### ISSUE TITLE
lxd init fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by ericoporto** [ogra1/wine-2#1]
I am trying to follow your README. But it's failing on `lxd init` line.

    $ snap install lxd
    lxd 3.0.0 from 'canonical' installed
    $ lxd init
    Error: Failed to connect to local LXD: Get http://unix.socket/1.0: dial unix 
    /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory

I have the following on my computer:

    $ snapcraft --version
    snapcraft, version 2.42.1
    $ uname -a
    4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I don't know if this is relevant, but my computer uses Intel i7-7500U and has Secure Boot UEFI.

**Comment by ogra1** [comment]
looks like your lxd daemon did not start ... 
```snap services lxd```
and
```snap logs lxd.daemon```
will probably reveal something ...

**Comment by ericoporto** [comment]
Thanks. Since it's on my computer [I went the askubuntu route](https://askubuntu.com/questions/1041379/lxd-init-fails-on-ubuntu-16-04-xenial-xerus).
